version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - supabase_network_outbound_ai_sdr
    #depends_on:
    #  - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A src.celery_app.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      # Celery Broker and Backend URLs
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Flower specific configurations
      - FLOWER_BROKER_API=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=admin:password
      - FLOWER_PERSISTENT=True
      - FLOWER_DB=/data/flower.db
      - FLOWER_STATE_SAVE_INTERVAL=30000
      # Additional Celery configurations
      - CELERY_TIMEZONE=UTC
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
    volumes:
      - flower_data:/data
    restart: unless-stopped

networks:
  supabase_network_outbound_ai_sdr:
    external: true
  #db:
  #  image: supabase/postgres:15.1.0.117
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    - POSTGRES_USER=${DB_USER:-postgres}
  #    - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
  #    - POSTGRES_DB=${DB_NAME:-outbound_ai_sdr}
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #    - ./migrations:/docker-entrypoint-initdb.d
  #  restart: unless-stopped

  # Uncomment if you want to add pgAdmin for database management
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   restart: unless-stopped

#volumes:
#  postgres_data: 

volumes:
  redis_data: 
  flower_data: